name: "Random xkcd meme generator"

on:
  fork: {}
  workflow_dispatch:
    inputs:
      create-meme-file:
        description: "Create a new meme file"

jobs:
  new_file_with_meme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate XKCD Comic URL
        id: generate_comic_url
        run: |
          python -c "import requests; import random; response = requests.get(f'https://xkcd.com/{random.randint(1, 2777)}/info.0.json'); comic_url = response.json()['img']; print(comic_url)"
        env:
          PYTHONUNBUFFERED: 1

      - name: Create new file in forked repo
        id: create_file
        run: |
          echo "Click here for a random XKCD meme: ${{ steps.generate_comic_url.outputs.comic_url }}" > MemeOfTheFork.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Added new file with XKCD Meme"
          git push origin HEAD
