#The earlier Idea had to be trashed because apparently I do not have write access to a created forked repo.
#Now I am implementing another idea, I will just generate an automated reply to any issue created, and include a random xkcd meme in that
